
namespace CBS.Models
{
    public enum TaskEventType
    {
        UPDATE_PROFILE_EXP_MULTIPLY = 0,
        RESET_PROFILE_LEADERBOARD = 1,
        ENANLE_OR_DISABLE_STORE = 2,
        SET_STORE_ITEM_PRICE = 3,
        ENABLE_OR_DISABLE_ITEM_IN_STORE = 4,
        START_STORE_GLOBAL_SPECIAL_OFFER = 5,
        STOP_STORE_GLOBAL_SPECIAL_OFFER = 6,
        SEND_MESSAGE_TO_CHAT = 7,
        ENABLE_OR_DISABLE_CALENDAR = 8,
        START_BATTLE_PASS = 9,
        STOP_BATTLE_PASS = 10,
        SEND_NOTIFICATION = 11,
        UPDATE_TITLE_DATA = 12,
        EXECUTE_FUNCTION = 13,
        REWARD_MEMBERS_OF_TOP_CLAN = 14,
        EXECUTE_EVENTS_FOR_MEMBERS_OF_TOP_CLAN = 15,
    }
}
